DM-15111: NCSA DUO and change to ~/notebooks are browser root
lsst-dm/nb_lsst_io pull request #6
Opened 2018-07-27 20:50 UTC by jonathansick

- Updates the log in docs to take into account NCSA DUO (mostly defers to the NCSA documentation)

- Changes related to `~/notebooks` no longer being privileged as the file browser root.

2018-07-27 22:10 UTC, athornton requested changes
Turns out that the Jellybean $HOME is /jhome on lsst-dev, accessed via $HOME/jhome .

Other than that, looks good.

2018-07-27 23:32 UTC, ktlim commented on environment/directories.rst
> +:file:`$HOME` is backed by essentially the same storage as your home directory on `lsst-dev`_ in the LSST Data Facility.
Note that we will soon (or already do?) have a class of notebook users who are not staff and do not have home directories on `lsst-dev`.

2018-07-27 23:33 UTC, ktlim commented on getting-started/logging-in.rst
> +- Install the `Cisco AnyConnect client`_ on you computer.
"you" -> "your"

2018-07-28 02:07 UTC, jonathansick commented
<img width="646" alt="screen shot 2018-07-27 at 7 07 06 pm" src="https://user-images.githubusercontent.com/349384/43351975-4de00972-91d0-11e8-8ca6-6b13035d4aad.png">

I think this language in the note should address all the concerns.

2018-07-28 14:35 UTC, merged